site_name: Jzon Documentation
theme:
  name: material
  palette:
    primary: red
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false # Use Highlight.js, not Pygments
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/highlight.min.js
  - js/res-syntax-highlightjs.js
  - js/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/default.min.css
nav:
  - "Getting Started": index.md
  - "How-to Guides": howtos.md
  - "API Reference": api.md
